//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LinkUrl { get; set; }
        public int NewsCategoryId { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
